# Settings
wandb: True
plot: True

# WandB
project_name : 'periodic_layer_where_predefined_when'
run_name: "guaInit_small"

# Methods
when_type: 'predefined'
where_type: 'add_n_with_random_layer'
how_type: 'autogrow_gauinit'
grow_neu_type: 'adding'
grow_lay_type: 'baseline'

# Dataset
dataset: 'mnist'
num_classes: 10
batch_size: 128
split_rate: [80, 19, 1]

# Training
epochs: 5
max_epochs: 4
growing: True
max_training: 5
neuron_growth: 5
seed: 42
optimiser: 'Adam'
init_architecture: [5]
activation_function: 'relu'
model_type: 'MLP'
learning_step: 0.001
loss_function: 'SparseCategoricalCrossentropy'
metric: 'SparseCategoricalAccuracy'